# Generated by Django 4.0.5 on 2022-06-20 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firearm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=8)),
                ('manufacturer', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=32)),
                ('caliber', models.CharField(max_length=32)),
                ('serial_number', models.CharField(max_length=32, null=True)),
                ('est_value', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('date_purchased', models.DateField(null=True)),
                ('notes', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='firearm',
            constraint=models.UniqueConstraint(fields=('type', 'manufacturer', 'model', 'serial_number'), name='Firearm model'),
        ),
    ]
